config/routes.rb
AngryRickshaw::Application.routes.draw do

	root to: 'home#home'
	resources :activity, only: [:index, :show]

	match '/map', to: 'map#map', as: 'map'

	match '/currency', to: 'currency#currency'

	match '/activity/', to: 'activity#index', as: 'all_activity'
	match '/activity/by_category/:category', to: 'activity#by_category', as: 'activity_by_category'

	match '/about', to: 'about#about'

	# it cares about routing errors, when given URL doesn't exist
	match '*a', to: 'errors#render_404'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	attr_accessible :name, :location

	belongs_to :location

	validates :name, presence: true
	validates :location, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name

	has_many :location

	validates :name, :presence => true
end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :address, :description, :latitude, :longitude, :name, :picture, :category

	belongs_to :category
	has_many :activity

	validates :name, presence: true
	validates :category_id, presence: true
	validates :longitude, :numericality => { :greater_than => -180, :less_than_or_equal_to => 180 }, presence: true
	validates :latitude, :numericality => { :greater_than => -90, :less_than_or_equal_to => 90 }, presence: true

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController

	before_filter :get_categories, :only => [:index, :by_category]

	def index
		redirect_to(activity_by_category_path(@categories.first))
	end

	def by_category
		if params[:category]
			@activities = Activity.includes(:location).where("locations.category_id = ?", params[:category])
		end

		render_404 if @activities.nil? || @activities.blank?
	end

	def show
		@activity = Activity.find(params[:id])

		rescue ActiveRecord::RecordNotFound
			render_404
	end

	def get_categories
		@categories = Category.all
	end

	def render_404
		respond_to do |format|
			format.html { render :file => "#{Rails.root}/public/404", :formats => [:html], :status => 404 }
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/currency_controller.rb
class CurrencyController < ApplicationController
  def currency
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
	def render_404
		respond_to do |format|
			format.html { render :file => "#{Rails.root}/public/404", :formats => [:html], :status => 404 }
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/activity_helper.rb
module ActivityHelper
	def image_map(location)
		zoom = 16
		marker_color = "red"
		map_width = 450
		map_height = 250
		"http://maps.google.com/maps/api/staticmap?center=#{location.latitude},#{location.longitude}&zoom=#{zoom}&size=#{map_width}x#{map_height}&markers=color:#{marker_color}%7Clabel:%7C#{location.latitude},#{location.longitude}&sensor=false"
	end

	def active_tab
		tab_number = 0
		if params[:category]
			tab_number = params[:category].to_i - 1
		end
		tab_number
	end

	def gmaps_url(location)
		"http://maps.google.com/maps?q=#{transform_string(location.name)},+#{transform_string(location.address)}&ll=#{location.latitude},#{location.longitude}"
	end

	def transform_string(address)
		address.gsub(" ", "+")
	end

	def short_description(description)
		desc_returned = description.dup
		if description.size >= 200
			desc_returned = description[0,197] << "..."
		end

		desc_returned
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Angry Rickshaw"
		if page_title.nil? || page_title.empty?
			base_title
		else
			"#{base_title} - #{page_title}"
		end
	end
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/about/about.html.erb
<% provide(:title, 'About Us') %>
<li class="span12">
	<section>

		<h2 id="aboutusTitle">About Us</h2>

		<p>We are ThoughtWorkers and we are awesome!</p>

		<h3>Authors</h3>

		<div class="profile">
			<%= image_tag("about/erlangga.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Erlangga Tjhie</b></p>

				<p><span><%= image_tag("about/indonesia.png", :class => 'flag') %></span> working in Melbourne,
					<span><%= image_tag("about/australia.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/greg.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Greg Skinner</b></p>

				<p><span><%= image_tag("about/uk.png", :class => 'flag') %></span> working in Melbourne,
					<span><%= image_tag("about/australia.png", :class => 'flag') %></span></p>

				<p>User Experience Designer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/johannes.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Johannes Thönes</b></p>

				<p><span><%= image_tag("about/germany.png", :class => 'flag') %></span> working in Hamburg,
					<span><%= image_tag("about/germany.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/jr.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Junior Ales</b></p>

				<p><span><%= image_tag("about/brazil.png", :class => 'flag') %></span> working in Porto Alegre,
					<span><%= image_tag("about/brazil.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/mewan.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Mewanbanjop Mawroh</b></p>

				<p><span><%= image_tag("about/india.png", :class => 'flag') %></span> working in Chennai,
					<span><%= image_tag("about/india.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/ruoran.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Ruoran Liu</b></p>

				<p><span><%= image_tag("about/china.png", :class => 'flag') %></span> working in Chengdu,
					<span><%= image_tag("about/china.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/solon.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Solon Aguiar</b></p>

				<p><span><%= image_tag("about/brazil.png", :class => 'flag') %></span> working in Porto Alegre,
					<span><%= image_tag("about/brazil.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

		<div class="profile">
			<%= image_tag("about/ste.jpg", :class => 'avatar') %>

			<div class="info">
				<p><b>Stephen Cowley</b></p>

				<p><span><%= image_tag("about/uk.png", :class => 'flag') %></span> working in Manchester,
					<span><%= image_tag("about/uk.png", :class => 'flag') %></span></p>

				<p>Developer</p>
			</div>
		</div>

	</section>
</li>

app/views/activity/activities.html.erb
<li class="span12">
	<section id="activityPageSection">
		<h2 id="activityPageTitle">Activities</h2>

		<ul id="activityMenu" class="nav nav-tabs">
			<% @categories.each do |cat| %>
				<li>
					<%= link_to cat.name, activity_map_path(cat, :anchor => "activityPageTitle") %>
				</li>
			<% end %>
		</ul>
		<ul id="activityLocations" class="row-fluid thumbnails">
			<% @activities.each do |act| %>
				<li class="thumbnail">
					<div class="span7">
						<img src="<%= image_map(act.location.latitude, act.location.longitude) %>">
					</div>
					<div class="span5 location-text">
						<h2><%= act.location.name %></h2>
						<h5><%= act.location.category.name %></h5>
						<p><%= act.location.description %></p>
					</div>
				</li>
			<% end %>
		</ul>
	</section>
	<script type="text/javascript">
		$('#activityMenu li:eq(<%= active_tab %>) a').tab('show');
	</script>
</li>

app/views/activity/by_category.html.erb
<% provide(:title, 'Activity') %>
<li class="span12">
	<section id="activitiesPageSection">
		<h2 id="activitiesPageTitle">Activities</h2>

		<ul id="activitiesMenu" class="nav nav-tabs">
			<% @categories.each do |cat| %>
				<li>
					<%= link_to cat.name, activity_by_category_path(cat, :anchor => "activitiesPageTitle") %>
				</li>
			<% end %>
		</ul>
		<ul id="activityLocations" class="row-fluid thumbnails">
			<% @activities.each do |act| %>
				<li class="thumbnail">
					<div class="span7">
						<img src="<%= image_map(act.location) %>">
					</div>
					<div class="span5">
						<div class="location-text">
							<h2><%= act.location.name %></h2>
							<h5><%= act.location.category.name %></h5>
							<p><%= short_description(act.location.description) %></p>
						</div>
						<div>
							<hr class="activity-row" />
							<%= link_to "Get Directions", gmaps_url(act.location), :class => "btn", :target => "_blank" %>
							<%= link_to "More Details", activity_path(act), :class => "btn" %>
						</div>
					</div>
				</li>
			<% end %>
		</ul>
	</section>
	<script type="text/javascript">
		$('#activitiesMenu li:eq(<%= active_tab %>) a').tab('show');
	</script>
</li>

app/views/activity/show.html.erb
<% provide(:title, @activity.location.name) %>
<li class="span12">
	<section id="activityPageSection">
		<ul class="row">
			<li id="activityInfo" class="span6">
				<div class="location-text">
					<%= image_tag(@activity.location.picture, :id => 'activityPhoto') %>
					<h2 id="activityName"><%= @activity.location.name %></h2>
					<h5 id="activityCategory"><%= @activity.name %></h5>
					<p id="activityDescription"><%= @activity.location.description %></p>
				</div>
				<div style="text-align: right;">
					<hr class="activity-row" />
					<% category = @activity.location.category %>
					<%= link_to "More #{category.name}", activity_by_category_path(category), :class => "btn" %>
					<%= link_to "All Categories", all_activity_path, :class => "btn" %>
				</div>
			</li>
			<li class="span5">
				<%= link_to gmaps_url(@activity.location) do %>
					<%= image_tag(image_map(@activity.location), :id => 'activityMap' ) %>
				<% end %>
			</li>
		</ul>
	</section>
</li>

app/views/currency/currency.html.erb
<% provide(:title, 'Currency') %>
<li class="span12">
	<section>
		<h2>Currency</h2>
		<div class="row-fluid custom-note">
			<div class="span12">
				<div id="erlangga" class="note"><%= image_tag("currency/Erlangga_3.png") %></div>
				<div id="greg" class="note"><%= image_tag("currency/Greg_3.png") %></div>
				<div id="johannes" class="note"><%= image_tag("currency/Johannes_3.png") %></div>
				<div id="jr" class="note"><%= image_tag("currency/Jr_3.png") %></div>
				<div id="mewan" class="note"><%= image_tag("currency/Mewan_3.png") %></div>
				<div id="ruoran" class="note"><%= image_tag("currency/Ruoran_3.png") %></div>
				<div id="solon" class="note"><%= image_tag("currency/Solon_3.png") %></div>
				<div id="ste" class="note"><%= image_tag("currency/Ste_3.png") %></div>
			</div>
		</div>
		<div class="row-fluid custom-row">
			<div class="span12">
				<input id="amount" placeholder="Insert here the value you want"/>
			</div>
		</div>
		<div id="exchange-container" class="row-fluid custom-row">
			<div class="span6">
				<table id="otherToRupees"></table>
			</div>
			<div class="span6">
				<table id="rupeesToOther"></table>
			</div>
		</div>
		<div class="clear"></div>
		<div id="timestamp"></div>
	</section>
</li>

app/views/currency_exchange/currencyExchange.html.erb
<% provide(:title, 'Currency') %>
<li class="span12">
	<section>
		<h2>Currency</h2>
		<div class="row-fluid custom-note">
			<div class="span12">
				<div id="erlangga" class="note"><%= image_tag("currency/Erlangga_3.png") %></div>
				<div id="greg" class="note"><%= image_tag("currency/Greg_3.png") %></div>
				<div id="johannes" class="note"><%= image_tag("currency/Johannes_3.png") %></div>
				<div id="jr" class="note"><%= image_tag("currency/Jr_3.png") %></div>
				<div id="mewan" class="note"><%= image_tag("currency/Mewan_3.png") %></div>
				<div id="ruoran" class="note"><%= image_tag("currency/Ruoran_3.png") %></div>
				<div id="solon" class="note"><%= image_tag("currency/Solon_3.png") %></div>
				<div id="ste" class="note"><%= image_tag("currency/Ste_3.png") %></div>
			</div>
		</div>
		<div class="row-fluid custom-row">
			<div class="span12">
				<input id="amount" placeholder="Insert here the value you want"/>
			</div>
		</div>
		<div id="exchange-container" class="row-fluid custom-row">
			<div class="span6">
				<table id="otherToRupees"></table>
			</div>
			<div class="span6">
				<table id="rupeesToOther"></table>
			</div>
		</div>
		<div class="clear"></div>
		<div id="timestamp"></div>
	</section>
</li>

app/views/home/home.html.erb
<li class="span8 thumb">
    <%= link_to map_path, :class => "thumbnail map-thumb" do %>
        <h2>Map</h2>

        <p>
            Look at the Bangalore map and find places to go
        </p>
    <% end %>
    <ul class="thumbnails" style="margin-top: 20px;">
        <li class="span4">
            <%= link_to all_activity_path, :class => "thumbnail activities-thumb" do %>
                <h2>Activities</h2>

                <p>
                    Interesting places and activities in Bangalore
                </p>
            <% end %>
        </li>
        <li class="span4">
            <%= link_to about_path, :class => "thumbnail about-thumb" do %>
                <h2>About Us</h2>

                <p>
                    See any information about us
                </p>
            <% end %>
        </li>
    </ul>
</li>
<li class="span4 thumb">
    <%= link_to currency_path, :class => "thumbnail currency-thumb" do %>
        <h2>Currency</h2>

        <p style="min-height: 200px;">
            Convert currency between Indian Rupees and yours with the latest rate
        </p>
    <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<ul class="thumbnails">
				<li class="span12">
					<%= link_to root_path do %>
						<section class="main-section">
							<div class="row-fluid">
								<div class="span8">
									<h1>Angry Rickshaw</h1><br/>
									<p>Hey gringo, get out of my land!!!</p>
								</div>
								<div class="span4">
									<%= image_tag("angry_rickshaw.png", :width => "240", :height => "220") %>
								</div>
							</div>
						</section>
					<% end %>
				</li>
				<%= yield %>
			</ul>
		</div>
	</body>
</html>

app/views/map/index.html.erb
<li class="span12">
	<section id="mapPageSection">
		<h2 id="mapPageTitle">Map</h2>

		<ul id="mapMenu" class="nav nav-tabs">
			<% @categories.each do |cat| %>
				<li>
					<%= link_to cat.name, location_map_path(cat, :anchor => "mapPageTitle") %>
				</li>
			<% end %>
		</ul>
		<ul id="mapLocations" class="row-fluid thumbnails">
			<% @locations.each do |loc| %>
				<li class="thumbnail">
					<div class="span7">
						<img src="<%= image_map(loc.latitude, loc.longitude) %>">
					</div>
					<div class="span5 location-text">
						<h2><%= loc.name %></h2>
						<h5><%= loc.category.name %></h5>
						<p><%= loc.description %></p>
					</div>
				</li>
			<% end %>
		</ul>
	</section>
</li>

app/views/map/map.html.erb
<% provide(:title, 'Map') %>
<li class="span12">
	<section id="mapPageSection">
		<h2 id="mapPageTitle">Map</h2>
	</section>
</li>